language: node_js
node_js:
    - 4
    - 6
    - 7
    - 8
script: "npm run-script cover"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  email:
    - lilleman@larvit.se
