group = core
admin-port = 13000
admin-password = kanneladmin
smsbox-port = 13001
log-level = 0
dlr-storage = internal

group = smsc
smsc = smpp
smsc-id = node-maxp1
host = node
port = 2775
smsc-username = kannel-maxp1
smsc-password = kannelpw
system-type = "kannel-esme"
transceiver-mode = true
interface-version = "34"
enquire-link-interval = 5
max-pending-submits = 1
reconnect-delay = 1
wait-ack = 5

group = smsbox
bearerbox-host = kannel-maxp1-bearerbox
sendsms-port = 13013
global-sender = 46700000000
http-request-retry = 3
http-queue-delay = 1

group = sendsms-user
username = tester
password = testerpw
max-messages = 10
concatenation = true

group = sms-service
keyword = default
get-url = "http://node:8080/mo/maxp1?from=%p&to=%P&text=%a&coding=%c&udh=%u"
max-messages = 0
omit-empty = true
